name = "eduplay-frontend"
compatibility_date = "2025-10-19"

pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "eduplay-auth"
database_id = "61998541-90f8-4ad5-94e1-44ee37fb215d"

