# Plantilla de configuración para Cloudflare Pages + Functions.
# Copia este archivo y ajusta los valores antes de desplegar.
name = "eduplay-frontend"
compatibility_date = "2024-05-01"
pages_build_output_dir = "."

[vars]
# Genera una cadena aleatoria de al menos 32 caracteres.
SESSION_SECRET = "changeme-super-secreto"

[[d1_databases]]
# Nombre del binding usado en el código (env.DB)
binding = "DB"
# Nombre de la base de datos en Cloudflare D1
# Sustituye por el identificador real de tu base en cada entorno.
database_name = "eduplay-auth"
database_id = "00000000-0000-0000-0000-000000000000"

# Para aplicar migraciones:
#   npm run migrations:apply        # entorno remoto
#   npm run migrations:apply:local  # entorno local con wrangler dev
#   npm run migrations:list         # estado de migraciones
